### ISSUE TITLE
Cpu process still detected running at 100%

### ISSUE THREAD

**Issue by p4n1k** [alfonmga/hiding-cryptominers-linux-rootkit#2]
In HTOP, process name has been successfully hidden, but cpu is still detected running at 100%
![Untitled](https://user-images.githubusercontent.com/46290080/149881820-79372c01-cc9a-4cea-b5ca-ed981cc3f4e9.png)

**Comment by alfonmga** [comment]
Please provide more info about what machine you're running it on, thanks.

**Comment by p4n1k** [comment]
> Please provide more info about the machine you're running it on, thanks.

i'm running with vagrant on generic/ubuntu2004 kernel version 5.4.0-66-generic

**Comment by p4n1k** [comment]
@alfonmga 
looks like khook is not working properly.
or does this module need to be signed?

**Comment by alfonmga** [comment]
> > Please provide more info about the machine you're running it on, thanks.
> 
> i'm running with vagrant on generic/ubuntu2004 kernel version 5.4.0-66-generic

Thanks for sharing. I'll try to reproduce it as soon as I have some time for this.

> @alfonmga
> looks like khook is not working properly.
> or does this module need to be signed?

Nope. It doesn't need to be signed. It should _just_ works.

**Comment by aadiljaleel** [comment]
I've a fix. Can I create pull request?
